spring.application.name=pams_backend_spring
server.port=9090
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/pamsbackend?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.file.name=logs/app.log
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


